name: WhatsApp Bot

# Eventos que acionam o workflow
on:
  push:
    branches:
      - main  # Executar quando houver push na branch 'main'
  workflow_dispatch:  # Permite execução manual através do GitHub

jobs:
  run-whatsapp-bot:
    runs-on: ubuntu-latest  # Ambiente do GitHub Actions

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2  # Faz o checkout do código

      - name: Set up Node.js
        uses: actions/setup-node@v2  # Instala o Node.js
        with:
          node-version: '16'  # Versão do Node.js

      - name: Install dependencies
        run: npm install  # Instala as dependências do projeto

      - name: Run WhatsApp bot
        run: node bot.js  # Executa o código do bot
        env:
          WA_SESSION: ${{ secrets.WA_SESSION }}  # Usando as credenciais salvas no GitHub Secrets
