name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # Configuração do Git para o GitHub Actions
      - name: Set up Git for GitHub Actions
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      # Instala as dependências
      - name: Install dependencies
        run: npm install

      # Realiza o commit das mudanças (se houver) no package-lock.json
      - name: Commit changes
        run: |
          git add package-lock.json
          git commit -m "Update package-lock.json" || echo "No changes to commit"
          git push

  # Adicione outros jobs se necessário
