name: Run WhatsApp Bot

on:
  push:
    branches:
      - main

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run the bot
        run: node bot.js

      - name: Upload QR Code
        uses: actions/upload-artifact@v2
        with:
          name: qr_code_image
          path: qr_code.png
