name: Run Bot on GitHub Actions

on:
  push:
    branches:
      - main  # A branch que vai disparar o workflow
  pull_request:
    branches:
      - main  # A branch que vai disparar o workflow

jobs:
  build:
    runs-on: ubuntu-latest  # Ambiente de execução

    steps:
      # Passo 1: Fazer checkout do código do repositório
      - name: Checkout repository
        uses: actions/checkout@v2

      # Passo 2: Configurar o Node.js (definindo a versão)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Versão do Node.js, ajuste conforme necessário

      # Passo 3: Instalar as dependências do projeto
      - name: Install dependencies
        run: npm install

      # Passo 4: Rodar o bot.js
      - name: Run bot.js
        env:
          WA_TOKEN: ${{ secrets.WA_TOKEN }}  # Acesso ao token armazenado nos GitHub Secrets
        run: node bot.js
