name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies (npm install)
        run: |
          npm install  # Garante que o package-lock.json seja gerado ou atualizado

      - name: Commit package-lock.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add package-lock.json
          git commit -m "Update package-lock.json" || echo "No changes to commit"
          git push

      - name: Run tests (npm ci)
        run: |
          npm ci  # Agora o npm ci pode ser executado com o package-lock.json atualizado

      - name: Run bot (example)
        run: |
          node bot.js
